### PR TITLE
Create Rohit_Kumar_Rohit-kmr.md

### PR DESCRIPTION
**Pull request by Rohit-Kmr**

### CODE REVIEW

**Comment by Rohit-Kmr** [comment]
please merge as you like

**Comment by kindacoder** [comment]
@Rohit-Kmr  have you followed all the guidelines ?

**Comment by kindacoder** [comment]
@Rohit-Kmr  are you really serious about contributing ? Or should I reject the pull request?

**Comment by Rohit-Kmr** [comment]
sorry i did not found any guidelines in the issue page so i thought it was like that
i have changed it now please check it @kindacoder

**Comment by Rohit-Kmr** [comment]
i am inexperienced in using git hub ( like i came to know about .md file today 😅) 
so i was learning how to use markdown files and was in middle of editing when you added the label

**Comment by kindacoder** [comment]
> i am inexperienced in using git hub ( like i came to know about .md file today )
> so i was learning how to use markdown files and was in middle of editing when you added the label

No problem @Rohit-Kmr . I am always here to help. By the way good try . Now I am merging it :+1:

**Pull request merged**
